//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
using System.Collections.Immutable;
using System.Diagnostics.CodeAnalysis;
using System.Runtime.CompilerServices;
using System.Text.Json;
using Corvus.Json;
using Corvus.Json.Internal;

namespace Caers.Api;
/// <summary>
/// A type generated from a JsonSchema specification.
/// </summary>
public readonly partial struct DeleteReportingPeriodDataType
{
    /// <summary>
    /// JSON property name for <see cref = "EmissionOperatingTypeCode"/>.
    /// </summary>
    public static ReadOnlySpan<byte> EmissionOperatingTypeCodeUtf8JsonPropertyName => "emissionOperatingTypeCode"u8;

    /// <summary>
    /// JSON property name for <see cref = "EmissionOperatingTypeCode"/>.
    /// </summary>
    public const string EmissionOperatingTypeCodeJsonPropertyName = "emissionOperatingTypeCode";
    /// <summary>
    /// JSON property name for <see cref = "ReportingPeriodTypeCode"/>.
    /// </summary>
    public static ReadOnlySpan<byte> ReportingPeriodTypeCodeUtf8JsonPropertyName => "reportingPeriodTypeCode"u8;

    /// <summary>
    /// JSON property name for <see cref = "ReportingPeriodTypeCode"/>.
    /// </summary>
    public const string ReportingPeriodTypeCodeJsonPropertyName = "reportingPeriodTypeCode";
    /// <summary>
    /// Gets EmissionOperatingTypeCode.
    /// </summary>
    public Corvus.Json.JsonString EmissionOperatingTypeCode
    {
        get
        {
            if ((this.backing & Backing.JsonElement) != 0)
            {
                if (this.jsonElementBacking.ValueKind != JsonValueKind.Object)
                {
                    return default;
                }

                if (this.jsonElementBacking.TryGetProperty(EmissionOperatingTypeCodeUtf8JsonPropertyName, out JsonElement result))
                {
                    return new Corvus.Json.JsonString(result);
                }
            }

            if ((this.backing & Backing.Object) != 0)
            {
                if (this.objectBacking.TryGetValue(EmissionOperatingTypeCodeJsonPropertyName, out JsonAny result))
                {
                    return result.As<Corvus.Json.JsonString>();
                }
            }

            return default;
        }
    }

    /// <summary>
    /// Gets ReportingPeriodTypeCode.
    /// </summary>
    public Corvus.Json.JsonString ReportingPeriodTypeCode
    {
        get
        {
            if ((this.backing & Backing.JsonElement) != 0)
            {
                if (this.jsonElementBacking.ValueKind != JsonValueKind.Object)
                {
                    return default;
                }

                if (this.jsonElementBacking.TryGetProperty(ReportingPeriodTypeCodeUtf8JsonPropertyName, out JsonElement result))
                {
                    return new Corvus.Json.JsonString(result);
                }
            }

            if ((this.backing & Backing.Object) != 0)
            {
                if (this.objectBacking.TryGetValue(ReportingPeriodTypeCodeJsonPropertyName, out JsonAny result))
                {
                    return result.As<Corvus.Json.JsonString>();
                }
            }

            return default;
        }
    }

    /// <summary>
    /// Creates an instance of a <see cref = "DeleteReportingPeriodDataType"/>.
    /// </summary>
    public static DeleteReportingPeriodDataType Create(Corvus.Json.JsonString reportingPeriodTypeCode, Corvus.Json.JsonString? emissionOperatingTypeCode = null)
    {
        var builder = ImmutableDictionary.CreateBuilder<JsonPropertyName, JsonAny>();
        builder.Add(ReportingPeriodTypeCodeJsonPropertyName, reportingPeriodTypeCode.AsAny);
        if (emissionOperatingTypeCode is Corvus.Json.JsonString emissionOperatingTypeCode__)
        {
            builder.Add(EmissionOperatingTypeCodeJsonPropertyName, emissionOperatingTypeCode__.AsAny);
        }

        return builder.ToImmutable();
    }

    /// <summary>
    /// Sets emissionOperatingTypeCode.
    /// </summary>
    /// <param name = "value">The value to set.</param>
    /// <returns>The entity with the updated property.</returns>
    public DeleteReportingPeriodDataType WithEmissionOperatingTypeCode(in Corvus.Json.JsonString value)
    {
        return this.SetProperty(EmissionOperatingTypeCodeJsonPropertyName, value);
    }

    /// <summary>
    /// Sets reportingPeriodTypeCode.
    /// </summary>
    /// <param name = "value">The value to set.</param>
    /// <returns>The entity with the updated property.</returns>
    public DeleteReportingPeriodDataType WithReportingPeriodTypeCode(in Corvus.Json.JsonString value)
    {
        return this.SetProperty(ReportingPeriodTypeCodeJsonPropertyName, value);
    }

    private static ValidationContext __CorvusValidateReportingPeriodTypeCode(in JsonObjectProperty property, in ValidationContext validationContext, ValidationLevel level)
    {
        return property.ValueAs<Corvus.Json.JsonString>().Validate(validationContext, level);
    }

    private static ValidationContext __CorvusValidateEmissionOperatingTypeCode(in JsonObjectProperty property, in ValidationContext validationContext, ValidationLevel level)
    {
        return property.ValueAs<Corvus.Json.JsonString>().Validate(validationContext, level);
    }

    /// <summary>
    /// Tries to get the validator for the given property.
    /// </summary>
    /// <param name = "property">The property for which to get the validator.</param>
    /// <param name = "hasJsonElementBacking"><c>True</c> if the object containing the property has a JsonElement backing.</param>
    /// <param name = "propertyValidator">The validator for the property, if provided by this schema.</param>
    /// <returns><c>True</c> if the validator was found.</returns>
    private bool __TryGetCorvusLocalPropertiesValidator(in JsonObjectProperty property, bool hasJsonElementBacking, [NotNullWhen(true)] out ObjectPropertyValidator? propertyValidator)
    {
        if (hasJsonElementBacking)
        {
            if (property.NameEquals(ReportingPeriodTypeCodeUtf8JsonPropertyName))
            {
                propertyValidator = __CorvusValidateReportingPeriodTypeCode;
                return true;
            }
            else if (property.NameEquals(EmissionOperatingTypeCodeUtf8JsonPropertyName))
            {
                propertyValidator = __CorvusValidateEmissionOperatingTypeCode;
                return true;
            }
        }
        else
        {
            if (property.NameEquals(ReportingPeriodTypeCodeJsonPropertyName))
            {
                propertyValidator = __CorvusValidateReportingPeriodTypeCode;
                return true;
            }
            else if (property.NameEquals(EmissionOperatingTypeCodeJsonPropertyName))
            {
                propertyValidator = __CorvusValidateEmissionOperatingTypeCode;
                return true;
            }
        }

        propertyValidator = null;
        return false;
    }
}