//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
using System.Collections.Immutable;
using System.Diagnostics.CodeAnalysis;
using System.Runtime.CompilerServices;
using System.Text.Json;
using Corvus.Json;
using Corvus.Json.Internal;

namespace Caers.Api;
/// <summary>
/// A type generated from a JsonSchema specification.
/// </summary>
public readonly partial struct Pollutant
{
    /// <summary>
    /// JSON property name for <see cref = "PollutantCasId"/>.
    /// </summary>
    public static ReadOnlySpan<byte> PollutantCasIdUtf8JsonPropertyName => "pollutantCasId"u8;

    /// <summary>
    /// JSON property name for <see cref = "PollutantCasId"/>.
    /// </summary>
    public const string PollutantCasIdJsonPropertyName = "pollutantCasId";
    /// <summary>
    /// JSON property name for <see cref = "PollutantCode"/>.
    /// </summary>
    public static ReadOnlySpan<byte> PollutantCodeUtf8JsonPropertyName => "pollutantCode"u8;

    /// <summary>
    /// JSON property name for <see cref = "PollutantCode"/>.
    /// </summary>
    public const string PollutantCodeJsonPropertyName = "pollutantCode";
    /// <summary>
    /// JSON property name for <see cref = "PollutantName"/>.
    /// </summary>
    public static ReadOnlySpan<byte> PollutantNameUtf8JsonPropertyName => "pollutantName"u8;

    /// <summary>
    /// JSON property name for <see cref = "PollutantName"/>.
    /// </summary>
    public const string PollutantNameJsonPropertyName = "pollutantName";
    /// <summary>
    /// Gets PollutantCasId.
    /// </summary>
    public Corvus.Json.JsonString PollutantCasId
    {
        get
        {
            if ((this.backing & Backing.JsonElement) != 0)
            {
                if (this.jsonElementBacking.ValueKind != JsonValueKind.Object)
                {
                    return default;
                }

                if (this.jsonElementBacking.TryGetProperty(PollutantCasIdUtf8JsonPropertyName, out JsonElement result))
                {
                    return new Corvus.Json.JsonString(result);
                }
            }

            if ((this.backing & Backing.Object) != 0)
            {
                if (this.objectBacking.TryGetValue(PollutantCasIdJsonPropertyName, out JsonAny result))
                {
                    return result.As<Corvus.Json.JsonString>();
                }
            }

            return default;
        }
    }

    /// <summary>
    /// Gets PollutantCode.
    /// </summary>
    public Caers.Api.Pollutant.PollutantCodeEntity PollutantCode
    {
        get
        {
            if ((this.backing & Backing.JsonElement) != 0)
            {
                if (this.jsonElementBacking.ValueKind != JsonValueKind.Object)
                {
                    return default;
                }

                if (this.jsonElementBacking.TryGetProperty(PollutantCodeUtf8JsonPropertyName, out JsonElement result))
                {
                    return new Caers.Api.Pollutant.PollutantCodeEntity(result);
                }
            }

            if ((this.backing & Backing.Object) != 0)
            {
                if (this.objectBacking.TryGetValue(PollutantCodeJsonPropertyName, out JsonAny result))
                {
                    return result.As<Caers.Api.Pollutant.PollutantCodeEntity>();
                }
            }

            return default;
        }
    }

    /// <summary>
    /// Gets PollutantName.
    /// </summary>
    public Corvus.Json.JsonString PollutantName
    {
        get
        {
            if ((this.backing & Backing.JsonElement) != 0)
            {
                if (this.jsonElementBacking.ValueKind != JsonValueKind.Object)
                {
                    return default;
                }

                if (this.jsonElementBacking.TryGetProperty(PollutantNameUtf8JsonPropertyName, out JsonElement result))
                {
                    return new Corvus.Json.JsonString(result);
                }
            }

            if ((this.backing & Backing.Object) != 0)
            {
                if (this.objectBacking.TryGetValue(PollutantNameJsonPropertyName, out JsonAny result))
                {
                    return result.As<Corvus.Json.JsonString>();
                }
            }

            return default;
        }
    }

    /// <summary>
    /// Creates an instance of a <see cref = "Pollutant"/>.
    /// </summary>
    public static Pollutant Create(Caers.Api.Pollutant.PollutantCodeEntity pollutantCode, Corvus.Json.JsonString? pollutantCasId = null, Corvus.Json.JsonString? pollutantName = null)
    {
        var builder = ImmutableDictionary.CreateBuilder<JsonPropertyName, JsonAny>();
        builder.Add(PollutantCodeJsonPropertyName, pollutantCode.AsAny);
        if (pollutantCasId is Corvus.Json.JsonString pollutantCasId__)
        {
            builder.Add(PollutantCasIdJsonPropertyName, pollutantCasId__.AsAny);
        }

        if (pollutantName is Corvus.Json.JsonString pollutantName__)
        {
            builder.Add(PollutantNameJsonPropertyName, pollutantName__.AsAny);
        }

        return builder.ToImmutable();
    }

    /// <summary>
    /// Sets pollutantCasId.
    /// </summary>
    /// <param name = "value">The value to set.</param>
    /// <returns>The entity with the updated property.</returns>
    public Pollutant WithPollutantCasId(in Corvus.Json.JsonString value)
    {
        return this.SetProperty(PollutantCasIdJsonPropertyName, value);
    }

    /// <summary>
    /// Sets pollutantCode.
    /// </summary>
    /// <param name = "value">The value to set.</param>
    /// <returns>The entity with the updated property.</returns>
    public Pollutant WithPollutantCode(in Caers.Api.Pollutant.PollutantCodeEntity value)
    {
        return this.SetProperty(PollutantCodeJsonPropertyName, value);
    }

    /// <summary>
    /// Sets pollutantName.
    /// </summary>
    /// <param name = "value">The value to set.</param>
    /// <returns>The entity with the updated property.</returns>
    public Pollutant WithPollutantName(in Corvus.Json.JsonString value)
    {
        return this.SetProperty(PollutantNameJsonPropertyName, value);
    }

    private static ValidationContext __CorvusValidatePollutantCode(in JsonObjectProperty property, in ValidationContext validationContext, ValidationLevel level)
    {
        return property.ValueAs<Caers.Api.Pollutant.PollutantCodeEntity>().Validate(validationContext, level);
    }

    private static ValidationContext __CorvusValidatePollutantName(in JsonObjectProperty property, in ValidationContext validationContext, ValidationLevel level)
    {
        return property.ValueAs<Corvus.Json.JsonString>().Validate(validationContext, level);
    }

    private static ValidationContext __CorvusValidatePollutantCasId(in JsonObjectProperty property, in ValidationContext validationContext, ValidationLevel level)
    {
        return property.ValueAs<Corvus.Json.JsonString>().Validate(validationContext, level);
    }

    /// <summary>
    /// Tries to get the validator for the given property.
    /// </summary>
    /// <param name = "property">The property for which to get the validator.</param>
    /// <param name = "hasJsonElementBacking"><c>True</c> if the object containing the property has a JsonElement backing.</param>
    /// <param name = "propertyValidator">The validator for the property, if provided by this schema.</param>
    /// <returns><c>True</c> if the validator was found.</returns>
    private bool __TryGetCorvusLocalPropertiesValidator(in JsonObjectProperty property, bool hasJsonElementBacking, [NotNullWhen(true)] out ObjectPropertyValidator? propertyValidator)
    {
        if (hasJsonElementBacking)
        {
            if (property.NameEquals(PollutantCodeUtf8JsonPropertyName))
            {
                propertyValidator = __CorvusValidatePollutantCode;
                return true;
            }
            else if (property.NameEquals(PollutantNameUtf8JsonPropertyName))
            {
                propertyValidator = __CorvusValidatePollutantName;
                return true;
            }
            else if (property.NameEquals(PollutantCasIdUtf8JsonPropertyName))
            {
                propertyValidator = __CorvusValidatePollutantCasId;
                return true;
            }
        }
        else
        {
            if (property.NameEquals(PollutantCodeJsonPropertyName))
            {
                propertyValidator = __CorvusValidatePollutantCode;
                return true;
            }
            else if (property.NameEquals(PollutantNameJsonPropertyName))
            {
                propertyValidator = __CorvusValidatePollutantName;
                return true;
            }
            else if (property.NameEquals(PollutantCasIdJsonPropertyName))
            {
                propertyValidator = __CorvusValidatePollutantCasId;
                return true;
            }
        }

        propertyValidator = null;
        return false;
    }
}