//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
using System.Collections.Immutable;
using System.Diagnostics.CodeAnalysis;
using System.Runtime.CompilerServices;
using System.Text.Json;
using Corvus.Json;
using Corvus.Json.Internal;

namespace Caers.Api;
/// <summary>
/// A type generated from a JsonSchema specification.
/// </summary>
public readonly partial struct State
{
    /// <summary>
    /// JSON property name for <see cref = "Code"/>.
    /// </summary>
    public static ReadOnlySpan<byte> CodeUtf8JsonPropertyName => "code"u8;

    /// <summary>
    /// JSON property name for <see cref = "Code"/>.
    /// </summary>
    public const string CodeJsonPropertyName = "code";
    /// <summary>
    /// JSON property name for <see cref = "FipsCode"/>.
    /// </summary>
    public static ReadOnlySpan<byte> FipsCodeUtf8JsonPropertyName => "fipsCode"u8;

    /// <summary>
    /// JSON property name for <see cref = "FipsCode"/>.
    /// </summary>
    public const string FipsCodeJsonPropertyName = "fipsCode";
    /// <summary>
    /// JSON property name for <see cref = "Name"/>.
    /// </summary>
    public static ReadOnlySpan<byte> NameUtf8JsonPropertyName => "name"u8;

    /// <summary>
    /// JSON property name for <see cref = "Name"/>.
    /// </summary>
    public const string NameJsonPropertyName = "name";
    /// <summary>
    /// Gets Code.
    /// </summary>
    public Caers.Api.State.CodeEntity Code
    {
        get
        {
            if ((this.backing & Backing.JsonElement) != 0)
            {
                if (this.jsonElementBacking.ValueKind != JsonValueKind.Object)
                {
                    return default;
                }

                if (this.jsonElementBacking.TryGetProperty(CodeUtf8JsonPropertyName, out JsonElement result))
                {
                    return new Caers.Api.State.CodeEntity(result);
                }
            }

            if ((this.backing & Backing.Object) != 0)
            {
                if (this.objectBacking.TryGetValue(CodeJsonPropertyName, out JsonAny result))
                {
                    return result.As<Caers.Api.State.CodeEntity>();
                }
            }

            return default;
        }
    }

    /// <summary>
    /// Gets FipsCode.
    /// </summary>
    public Caers.Api.State.FipsCodeEntity FipsCode
    {
        get
        {
            if ((this.backing & Backing.JsonElement) != 0)
            {
                if (this.jsonElementBacking.ValueKind != JsonValueKind.Object)
                {
                    return default;
                }

                if (this.jsonElementBacking.TryGetProperty(FipsCodeUtf8JsonPropertyName, out JsonElement result))
                {
                    return new Caers.Api.State.FipsCodeEntity(result);
                }
            }

            if ((this.backing & Backing.Object) != 0)
            {
                if (this.objectBacking.TryGetValue(FipsCodeJsonPropertyName, out JsonAny result))
                {
                    return result.As<Caers.Api.State.FipsCodeEntity>();
                }
            }

            return default;
        }
    }

    /// <summary>
    /// Gets Name.
    /// </summary>
    public Corvus.Json.JsonString Name
    {
        get
        {
            if ((this.backing & Backing.JsonElement) != 0)
            {
                if (this.jsonElementBacking.ValueKind != JsonValueKind.Object)
                {
                    return default;
                }

                if (this.jsonElementBacking.TryGetProperty(NameUtf8JsonPropertyName, out JsonElement result))
                {
                    return new Corvus.Json.JsonString(result);
                }
            }

            if ((this.backing & Backing.Object) != 0)
            {
                if (this.objectBacking.TryGetValue(NameJsonPropertyName, out JsonAny result))
                {
                    return result.As<Corvus.Json.JsonString>();
                }
            }

            return default;
        }
    }

    /// <summary>
    /// Creates an instance of a <see cref = "State"/>.
    /// </summary>
    public static State Create(Caers.Api.State.CodeEntity code, Caers.Api.State.FipsCodeEntity? fipsCode = null, Corvus.Json.JsonString? name = null)
    {
        var builder = ImmutableDictionary.CreateBuilder<JsonPropertyName, JsonAny>();
        builder.Add(CodeJsonPropertyName, code.AsAny);
        if (fipsCode is Caers.Api.State.FipsCodeEntity fipsCode__)
        {
            builder.Add(FipsCodeJsonPropertyName, fipsCode__.AsAny);
        }

        if (name is Corvus.Json.JsonString name__)
        {
            builder.Add(NameJsonPropertyName, name__.AsAny);
        }

        return builder.ToImmutable();
    }

    /// <summary>
    /// Sets code.
    /// </summary>
    /// <param name = "value">The value to set.</param>
    /// <returns>The entity with the updated property.</returns>
    public State WithCode(in Caers.Api.State.CodeEntity value)
    {
        return this.SetProperty(CodeJsonPropertyName, value);
    }

    /// <summary>
    /// Sets fipsCode.
    /// </summary>
    /// <param name = "value">The value to set.</param>
    /// <returns>The entity with the updated property.</returns>
    public State WithFipsCode(in Caers.Api.State.FipsCodeEntity value)
    {
        return this.SetProperty(FipsCodeJsonPropertyName, value);
    }

    /// <summary>
    /// Sets name.
    /// </summary>
    /// <param name = "value">The value to set.</param>
    /// <returns>The entity with the updated property.</returns>
    public State WithName(in Corvus.Json.JsonString value)
    {
        return this.SetProperty(NameJsonPropertyName, value);
    }

    private static ValidationContext __CorvusValidateCode(in JsonObjectProperty property, in ValidationContext validationContext, ValidationLevel level)
    {
        return property.ValueAs<Caers.Api.State.CodeEntity>().Validate(validationContext, level);
    }

    private static ValidationContext __CorvusValidateFipsCode(in JsonObjectProperty property, in ValidationContext validationContext, ValidationLevel level)
    {
        return property.ValueAs<Caers.Api.State.FipsCodeEntity>().Validate(validationContext, level);
    }

    private static ValidationContext __CorvusValidateName(in JsonObjectProperty property, in ValidationContext validationContext, ValidationLevel level)
    {
        return property.ValueAs<Corvus.Json.JsonString>().Validate(validationContext, level);
    }

    /// <summary>
    /// Tries to get the validator for the given property.
    /// </summary>
    /// <param name = "property">The property for which to get the validator.</param>
    /// <param name = "hasJsonElementBacking"><c>True</c> if the object containing the property has a JsonElement backing.</param>
    /// <param name = "propertyValidator">The validator for the property, if provided by this schema.</param>
    /// <returns><c>True</c> if the validator was found.</returns>
    private bool __TryGetCorvusLocalPropertiesValidator(in JsonObjectProperty property, bool hasJsonElementBacking, [NotNullWhen(true)] out ObjectPropertyValidator? propertyValidator)
    {
        if (hasJsonElementBacking)
        {
            if (property.NameEquals(CodeUtf8JsonPropertyName))
            {
                propertyValidator = __CorvusValidateCode;
                return true;
            }
            else if (property.NameEquals(FipsCodeUtf8JsonPropertyName))
            {
                propertyValidator = __CorvusValidateFipsCode;
                return true;
            }
            else if (property.NameEquals(NameUtf8JsonPropertyName))
            {
                propertyValidator = __CorvusValidateName;
                return true;
            }
        }
        else
        {
            if (property.NameEquals(CodeJsonPropertyName))
            {
                propertyValidator = __CorvusValidateCode;
                return true;
            }
            else if (property.NameEquals(FipsCodeJsonPropertyName))
            {
                propertyValidator = __CorvusValidateFipsCode;
                return true;
            }
            else if (property.NameEquals(NameJsonPropertyName))
            {
                propertyValidator = __CorvusValidateName;
                return true;
            }
        }

        propertyValidator = null;
        return false;
    }
}